### ISSUE TITLE
where are the mainnet genesis files?

### ISSUE THREAD

**Issue by jjordan-quantum** [shibaswaparmy/launch#14]
The README specifies the genesis files are in the bor/ and heimdall/ dirs, but there are many such dirs (none in repo base though).  Also I believe mainnet is chain 109 - everything I'm seeing in this repo is 137 or 719 in the genesis files.  Could we get the official genesis.json files used for mainnet uploaded here?

**Comment by kaber2** [comment]
Also, maybe a few seed nodes as I expect it will take a.long time to discover them otherwise...

**Comment by jjordan-quantum** [comment]
looks like genesis files were added since last time i checked. my bad
